image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo "Initialization completed"
  - command: |
      echo "Welcome to your Kali Linux Gitpod workspace!"
      ~/start_vnc.sh
      websockify -D --web=/usr/share/novnc/ 6080 localhost:5901

ports:
  - port: 5901
    onOpen: open-preview
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.cpptools
